post-build: use `GITHUB_ACTION_PATH` instead of `github.action_path`
```
Error: Homebrew/actions/master/post-build/action.yml: (Line: 60, Col: 57, Idx: 1765) - (Line: 60, Col: 78, Idx: 1786): While parsing a block mapping, did not find expected key.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Failed to load Homebrew/actions/master/post-build/action.yml
```

Signed-off-by: Rui Chen <rui@chenrui.dev>