download-artifact: use unzip command instead of library
Fixes:

```
==> Commit: 81c199f1238894c379d5e5e27433a734740ab1a4
[@octokit/paginate-rest] "response.data.workflow_runs" is deprecated for "GET /repos/Homebrew/linuxbrew-core/actions/workflows/build-bottles.yml/runs". Get the results directly from "response.data"
==> Run: 64961837
==> Artifact: 3504117
events.js:187
      throw er; // Unhandled 'error' event
      ^
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:170:17)
Emitted 'error' event on DuplexWrapper instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at DuplexWrapper.onerror (_stream_readable.js:759:7)
    at DuplexWrapper.emit (events.js:210:5)
    at Parse.<anonymous> (/__w/_actions/Homebrew/actions/master/download-artifact/node_modules/duplexer2/index.js:45:12)
    at Parse.emit (events.js:210:5)
    at InflateRaw.<anonymous> (/__w/_actions/Homebrew/actions/master/download-artifact/node_modules/unzipper/lib/parse.js:188:46)
    at InflateRaw.emit (events.js:210:5)
    at Zlib.zlibOnError [as onerror] (zlib.js:173:8) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```